Repository doctrine/deprecations, pull requests merged in 2023-06, with the labels that each got.

#45 Setup static analysis
  .github/workflows/static-analysis.yml
  composer.json
  phpstan.neon
  psalm.xml
Labels: CI

#49 Improve static analysis
  lib/Doctrine/Deprecations/Deprecation.php
  phpstan.neon
  psalm.xml
  tests/Doctrine/Deprecations/DeprecationTest.php
  tests/Doctrine/Deprecations/VerifyDeprecationsTest.php
Labels: Static Analysis

#47 Add the phpstan PHPUnit plugin
  composer.json
  phpstan.neon
Labels: Static Analysis

#48 Reach higher levels of static analysis
  lib/Doctrine/Deprecations/Deprecation.php
  psalm.xml
Labels: Static Analysis

#50 Normalize composer.json
  .github/workflows/composer-lint.yml
  composer.json
Labels: CI

#43 Fix Deprecation::ignoreDeprecations
  lib/Doctrine/Deprecations/Deprecation.php
  tests/Doctrine/Deprecations/DeprecationTest.php
Labels: bug

#51 Reach psalm level 2
  composer.json
  psalm.xml
Labels: Static Analysis

#52 Add better types for the sprintf-like arguments
  lib/Doctrine/Deprecations/Deprecation.php
Labels: Static Analysis

#54 Setup automatic releases
  .github/workflows/composer-lint.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#53 Fix deprecations triggered from code called by native code
  lib/Doctrine/Deprecations/Deprecation.php
  test_fixtures/src/ConstructorDeprecation.php
  tests/Doctrine/Deprecations/DeprecationTest.php
Labels: bug

#58 Reach psalm max level
  lib/Doctrine/Deprecations/Deprecation.php
  psalm.xml
  tests/Doctrine/Deprecations/DeprecationTest.php
Labels: Static Analysis

#56 Fix the state resetting between tests
  tests/Doctrine/Deprecations/DeprecationTest.php
Labels: test suite

#60 Add missing wildcard characters
  .github/workflows/static-analysis.yml
Labels: CI

#59 Run tooling on test fixtures directory
  .github/workflows/static-analysis.yml
  phpcs.xml
  phpstan.neon
  psalm.xml
  test_fixtures/src/ConstructorDeprecation.php
  test_fixtures/src/RootDeprecation.php
Labels: CI

#57 Reach the max level for phpstan
  phpstan.neon
Labels: Static Analysis

#61 Rework existing ci file
  .github/workflows/ci.yml
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
Labels: CI
